#!/usr/bin/env python3
"""Straw-man DUCS generator: pick ONE random Earthdata collection and emit a
self-contained Python code snippet (auth · search · navigate · access) for it.

This is a throwaway proof-of-the-loop, NOT the real pipeline. The real thing
(SPEC-001 / architecture.md) will send CMR metadata + a format->library lookup +
prior examples to an LLM, then executes-and-validates in Docker. Here we:

  1. auth via ~/.netrc
  2. randomly pick a cloud-hosted collection (spread across DAAC providers)
  3. pull the bits of UMM-C we'd feed a prompt
  4. confirm a real granule exists (the only "validation" in this straw-man)
  5. fill a template snippet, specialized by a tiny format->library table

Run:  python prototype/strawman_ducs.py [--seed N]
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import textwrap
from pathlib import Path

import earthaccess

# A spread of cloud-hosted DAAC providers so we sample across the archive
# instead of always taking the first-N-by-relevance from one query.
CLOUD_PROVIDERS = [
    "GES_DISC",
    "LPCLOUD",
    "POCLOUD",
    "NSIDC_CPRD",
    "ORNL_CLOUD",
    "ASF",
    "LARC_CLOUD",
    "OB_DAAC",
    "GHRC_DAAC",
    "SEDAC",
]

# Straw-man format -> (library, open-recipe) lookup. The real pipeline grows
# this into lookup/ with per-level/per-format rules.
FORMAT_LUT = [
    (("netcdf", "hdf5", "hdf-eos5", "he5"), "xarray", "ds = xr.open_dataset(files[0])"),
    (
        ("hdf4", "hdf-eos", "hdf-eos2", "hdf"),
        "xarray",
        'ds = xr.open_dataset(files[0], engine="netcdf4")  # needs libnetcdf built with HDF4',
    ),
    (
        ("geotiff", "cog", "tiff", "tif"),
        "rioxarray",
        "ds = rxr.open_rasterio(files[0])",
    ),
    (("zarr",), "xarray", 'ds = xr.open_dataset(files[0], engine="zarr")'),
    (("csv", "ascii", "text", "txt"), "pandas", "df = pd.read_csv(files[0])"),
]

IMPORTS = {
    "xarray": "import xarray as xr",
    "rioxarray": "import rioxarray as rxr",
    "pandas": "import pandas as pd",
}


def safe(d, *keys, default=None):
    """Walk nested dict/list keys, returning default on any miss."""
    cur = d
    for k in keys:
        try:
            cur = cur[k]
        except (KeyError, IndexError, TypeError):
            return default
    return cur


def pick_collection(rng) -> "earthaccess.results.DataCollection":
    """Randomly pick one cloud-hosted collection, spread across providers."""
    providers = rng.sample(CLOUD_PROVIDERS, len(CLOUD_PROVIDERS))
    for prov in providers:
        cols = earthaccess.search_datasets(cloud_hosted=True, provider=prov, count=80)
        if cols:
            return rng.choice(cols)
    # Fallback: broad cloud-hosted query.
    return rng.choice(earthaccess.search_datasets(cloud_hosted=True, count=200))


def derive_format(umm) -> str:
    fmt = safe(
        umm, "ArchiveAndDistributionInformation", "FileArchiveInformation", 0, "Format"
    )
    return (fmt or "").strip()


def choose_library(fmt: str, sample_url: str):
    hay = f"{fmt} {sample_url}".lower()
    for needles, lib, recipe in FORMAT_LUT:
        if any(n in hay for n in needles):
            return lib, recipe
    return None, None


def bbox_from(umm):
    br = safe(
        umm,
        "SpatialExtent",
        "HorizontalSpatialDomain",
        "Geometry",
        "BoundingRectangles",
        0,
    )
    if not br:
        return (-180, -90, 180, 90)
    return (
        br.get("WestBoundingCoordinate", -180),
        br.get("SouthBoundingCoordinate", -90),
        br.get("EastBoundingCoordinate", 180),
        br.get("NorthBoundingCoordinate", 90),
    )


def start_date(umm) -> str:
    return safe(
        umm,
        "TemporalExtents",
        0,
        "RangeDateTimes",
        0,
        "BeginningDateTime",
        default="2020-01-01T00:00:00Z",
    )[:10]


def build_snippet(meta: dict) -> str:
    lib = meta["library"]
    import_line = IMPORTS.get(lib, "")
    open_recipe = meta["open_recipe"] or (
        f'# No format->library rule for {meta["format"]!r}; open manually.\n'
        f'    print(files[0])'
    )
    w, s, e, n = meta["bbox"]
    return textwrap.dedent(f'''\
        """DUCS (straw-man) — {meta["short_name"]} v{meta["version"]}
        {meta["entry_title"]}
        Provider: {meta["provider"]} · Concept ID: {meta["concept_id"]}
        Format: {meta["format"] or "unknown"} · Processing level: L{meta["level"]}
        DOI: {meta["doi"]}
        Generated by prototype/strawman_ducs.py — template fill, not LLM output.
        """
        import earthaccess
        {import_line}

        # 1. AUTH ------------------------------------------------------------
        earthaccess.login()  # uses ~/.netrc or EARTHDATA_USERNAME/PASSWORD

        # 2. SEARCH (spatiotemporal) ----------------------------------------
        results = earthaccess.search_data(
            concept_id="{meta["concept_id"]}",
            temporal=("{meta["start"]}", "{meta["start"]}"),
            bounding_box=({w}, {s}, {e}, {n}),
            count=1,
        )
        print(f"Found {{len(results)}} granule(s)")

        # 3. NAVIGATE (open the file object) --------------------------------
        files = earthaccess.open(results)
        {open_recipe}

        # 4. ACCESS (inspect the data) --------------------------------------
        print({meta["inspect_expr"]})
    ''')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--seed", type=int, default=None, help="seed RNG for a reproducible pick"
    )
    args = ap.parse_args()
    rng = random.Random(args.seed)

    print("Authenticating via ~/.netrc ...")
    auth = earthaccess.login()
    if not auth.authenticated:
        print("ERROR: not authenticated", file=sys.stderr)
        return 1

    print("Picking a random cloud-hosted collection ...")
    col = pick_collection(rng)
    umm = col["umm"]
    concept_id = col.concept_id()

    print("Confirming a real granule exists (straw-man validation) ...")
    grans = earthaccess.search_data(concept_id=concept_id, count=1)
    sample_url = grans[0].data_links()[0] if grans else ""

    fmt = derive_format(umm)
    lib, recipe = choose_library(fmt, sample_url)
    inspect = {
        "xarray": "ds",
        "rioxarray": "ds",
        "pandas": "df.head()",
    }.get(lib, "files[0]")

    meta = {
        "concept_id": concept_id,
        "short_name": umm.get("ShortName", "?"),
        "version": umm.get("Version", "?"),
        "entry_title": umm.get("EntryTitle", ""),
        "provider": safe(col, "meta", "provider-id", default="?"),
        "doi": safe(umm, "DOI", "DOI", default="n/a"),
        "level": safe(umm, "ProcessingLevel", "Id", default="?"),
        "format": fmt,
        "library": lib or "none",
        "open_recipe": recipe,
        "inspect_expr": inspect,
        "bbox": bbox_from(umm),
        "start": start_date(umm),
        "n_granules": len(grans),
        "sample_url": sample_url,
    }

    print("\n=== Picked collection ===")
    for k in (
        "short_name",
        "version",
        "concept_id",
        "provider",
        "level",
        "format",
        "library",
        "doi",
        "n_granules",
    ):
        print(f"  {k:12}: {meta[k]}")
    print(f"  sample_url  : {sample_url}")

    snippet = build_snippet(meta)
    out_dir = Path(__file__).parent / "out"
    out_dir.mkdir(exist_ok=True)
    stem = f"{meta['short_name']}_{meta['version']}".replace("/", "-")
    (out_dir / f"{stem}.py").write_text(snippet)
    (out_dir / f"{stem}.meta.json").write_text(json.dumps(meta, indent=2))

    print(f"\n=== Generated snippet ({stem}.py) ===\n")
    print(snippet)
    print(f"Wrote {out_dir / (stem + '.py')}")
    print(
        "\nStraw-man validation:",
        "PASS (granule found + snippet emitted)"
        if grans
        else "WARN (no granule found for this collection)",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
